feat(NODE-xxxx): Add support for encrypted schemas
mongodb-js/mongoose pull request #5
Opened 2024-12-26 18:58 UTC by baileympearson

**Summary**

**Examples**

2025-01-15 14:41 UTC, baileympearson commented on .eslintrc.js
> +    '.config'
I added .config because I noticed lint failed after generating the docs locally, and `data` because otherwise the data for encrypted tests is linted.

2025-01-15 16:31 UTC, nbbeeken commented on lib/encryption_utils.js
> +  if (type instanceof Array) {
Just leaving a bread crumb, we wanted to pass along a question about this to Val.

2025-01-15 16:31 UTC, nbbeeken commented on test/encrypted_schema.test.js
> +      mongoose.Schema.Types.Int8 = Int8;
Should this be done in before/after? does it matter that there's now an Int8 type globally?

2025-01-15 16:31 UTC, nbbeeken commented on docs/field-level-encryption.md
> +}, { encryptionType: 'queryable encryption' });
In the kick off this is written as `encryptionType: 'qe'`, just wondering if this change was intentional? csfle is still an acronym, should we stick with qe?

2025-01-15 19:56 UTC, baileympearson commented on docs/field-level-encryption.md
> +}, { encryptionType: 'queryable encryption' });
'qe' was just me being lazy.  I don't feel strongly, but if I had to choose which to put in the public API, I would choose the approach that doesn't use acronyms.  Acronyms inevitably lead to confusion

2025-01-15 20:05 UTC, nbbeeken commented on docs/field-level-encryption.md
> +}, { encryptionType: 'queryable encryption' });
Sure I'm fine with that but it is slightly strange to have a space in it since it is kind of an enum, thoughts?

Maybe we don't need field-level in csfle?

```js
'queryableEncryption';
'clientSideEncryption';
```

2025-01-15 20:07 UTC, nbbeeken commented on test/encrypted_schema.test.js
> +      });
```suggestion
      beforeEach(function() {
        // Don't forget to add `Int8` to the type registry
        mongoose.Schema.Types.Int8 = Int8;
      });
      
      afterEach(function() {
        delete mongoose.Schema.Types.Int8;
      });
```

I haven't seen `this.` before those hooks, is that the same thing?

2025-01-15 20:24 UTC, baileympearson commented on test/encrypted_schema.test.js
> +      });
VSCode always defaults to `this.` - they're the same.  mocha just binds the free functions to the context that they're running in, calling the suite-level beforeEach: https://github.com/mochajs/mocha/blob/b720ec1b3ca630a90f80311da391b2a0cdfead4e/lib/mocha.js#L104

2025-01-15 21:10 UTC, nbbeeken requested changes

2025-01-15 21:10 UTC, nbbeeken commented on lib/schema.js
> + * - [encryptionType]: the encryption type for the schema.  Valid options are `csfle` or `queryable encryption`.  See https://mongoosejs.com/docs/field-level-encryption.
```suggestion
 * - [encryptionType]: the encryption type for the schema.  Valid options are `csfle` or `queryableEncryption`.  See https://mongoosejs.com/docs/field-level-encryption.
```

2025-01-15 21:22 UTC, nbbeeken approved these changes

2025-01-19 00:27 UTC, vkarpov15 commented on lib/encryption_utils.js
> +function inferBSONType(schema, path) {
Can we instead add these as a `getBSONType()` method on SchemaType class? That would make this more extensible for custom schematypes.

2025-01-19 00:30 UTC, vkarpov15 commented on lib/encryption_utils.js
> +'use strict';
For consistency, please name this file `lib/encryptionUtils.js`, Mongoose camelCases file names

2025-01-19 00:34 UTC, vkarpov15 commented on lib/schema.js
> +      if (this.encryptionType() != val.encryptionType()) {
Mongoose document arrays get implicitly created schemas, so `docArr: [{ name: String }]` implicitly creates a schema with `{ name: String }`. We pass certain schema options to implicitly created schemas, like `typeKey`. It might be worthwhile to make sure encryption type gets passed down as well.

2025-01-19 00:35 UTC, vkarpov15 commented on lib/schema.js
> +  this._encryptionType = options?.encryptionType;
Why is `_encryptionType` a separate property, instead of making `encryptionType()` get/set `options.encryptionType`? The latter would be more consistent with how Mongoose handles other options.

2025-01-22 16:36 UTC, baileympearson commented on lib/encryption_utils.js
> +function inferBSONType(schema, path) {
I can instead make it a getter on `SchemaType` - but this isn't intended to be extensible for custom schema types (see the `When a schema is instantiated with a custom schema type plugin` test).  

FLE has pretty strict requirements about which bson types are supported and I intentionally only supported the exact schema type that correspond to FLE's supported schema types.  Allowing users to provide custom schema types that get auto encrypted seems like it could confusion for users and opaque errors.  A hypothetical scenario: a custom schema type sometimes casts to a support BSON type, sometimes it doesn't, causing FLE to throw only sometimes for users.

I'm open to reconsidering though - we could instead support any SchemaType that casts to exactly one supported BSON type.  I'm not sure we could enforce this programmatically but documentation would probably suffice.  Would you prefer that approach?

2025-01-22 16:36 UTC, baileympearson commented on lib/schema.js
> +      if (this.encryptionType() != val.encryptionType()) {
Arrays are encrypted as an array, not by individual element.  So the logic here only creates a schemaType of type "array" - the contents of the array don't matter.  So encryptionType for the implicitly generated schemas shouldn't matter.

That being said, I'm happy to ensure that the encryption type gets propagated to sub-schemas if you'd like

2025-01-22 16:36 UTC, baileympearson commented on lib/encryption_utils.js
> +'use strict';
Does this apply to test files too?

2025-01-22 16:37 UTC, baileympearson commented on lib/schema.js
> +  this._encryptionType = options?.encryptionType;
Only because I didn't consider mutation the options object 🙂 .  Fixed!

2025-01-22 20:10 UTC, aditi-khare-mongoDB requested changes, later dismissed

2025-01-22 20:10 UTC, aditi-khare-mongoDB commented on docs/field-level-encryption.md
> +MongoDB has to different automatic encryption implementations: client side field level encryption (CSFLE) and queryable encryption (QE).
```suggestion
MongoDB has two different automatic encryption implementations: client side field level encryption (CSFLE) and queryable encryption (QE).  
```

2025-01-22 20:10 UTC, aditi-khare-mongoDB commented on lib/encryptionUtils.js
> + * @returns
```suggestion
 * @returns {string}
```
Or we can also just remove the line altogether. What do you think?

2025-01-22 20:10 UTC, aditi-khare-mongoDB commented on test/encrypted_schema.test.js
> +      describe('When omit() is used with some all the encrypted fields', function() {
```suggestion
      describe('When omit() is used with all the encrypted fields', function() {
```

2025-01-22 20:10 UTC, aditi-khare-mongoDB commented on test/encrypted_schema.test.js
> +          assert.equal(schema2.encryptionType(), 'csfle');
If we only `pick` unencrypted fields, the resulting schema's `options.encryptionType` is `null`. 

With the current implementation, if we `omit` all encrypted fields, the resulting schema's `options.encryptionType` is not `null`. What's our reasoning for this?

2025-01-30 18:46 UTC, vkarpov15 commented on .eslintrc.js
> +    '.config'
Works for me

2025-01-30 18:49 UTC, vkarpov15 commented on lib/encryption_utils.js
> +function inferBSONType(schema, path) {
I think I would prefer the more extensible approach just in case developers have their own custom type wrappers around built-in types. For example, users may still use mongoose-int32 for int32 support, or may have their own custom `Price` type that gets stored as an int32 under the hood. Using custom types like this isn't a pattern that the Mongoose docs recommend, but people do all sorts of surprising things.

2025-01-30 18:49 UTC, vkarpov15 commented on lib/encryption_utils.js
> +'use strict';
Yes

2025-01-30 18:52 UTC, vkarpov15 commented on lib/schema.js
> +      if (this.encryptionType() != val.encryptionType()) {
Ok, if encryption type doesn't matter for implicitly created schemas then that should be fine

2025-03-17 19:34 UTC, closed without merging